name: MySecondWorkflow

on: 
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  MySecondWorkflowSecondJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - run: | 
            echo " these are the files in ${{github.repository}}"
